const ACTION_PREFIX = '__redux__webworker';

export const SEND_MESSAGE = `${ACTION_PREFIX}:SEND_MESSAGE`;
export const SEND_MESSAGE_FAIL = `${ACTION_PREFIX}:SEND_MESSAGE_FAIL`;
export const SEND_MESSAGE_SUCCESS = `${ACTION_PREFIX}:SEND_MESSAGE_SUCCESS`;

export const EXECUTE_WORKER = `${ACTION_PREFIX}:EXECUTE_WORKER`;
export const EXECUTE_WORKER_FAIL = `${ACTION_PREFIX}:EXECUTE_WORKER_FAIL`;
export const EXECUTE_WORKER_SUCCESS = `${ACTION_PREFIX}:EXECUTE_WORKER_SUCCESS`;

export const TERMINATE_WORKER = `${ACTION_PREFIX}:TERMINATE_WORKER`;
export const TERMINATE_WORKER_FAIL = `${ACTION_PREFIX}:TERMINATE_WORKER_FAIL`;
export const TERMINATE_WORKER_SUCCESS = `${ACTION_PREFIX}:TERMINATE_WORKER_SUCCESS`;
